### ISSUE TITLE
not correct work with resource job_object

### ISSUE THREAD

**Issue by Insolita** [zhuravljov/yii2-queue-monitor#1]
https://github.com/zhuravljov/yii2-queue-monitor/blob/master/src/records/PushRecord.php#L153

```php

/**
     * @return Job|mixed
     */
    public function getJob()
    {
        if ($this->_job === null) {
           if(is_resource($this->job_object)){
                $this->job_object = stream_get_contents($this->job_object);
           }
            $this->_job = unserialize($this->job_object);
        }
        return $this->_job;
    }

```

or same check on afterFind event
(Db - Postgresql)

**Comment by zhuravljov** [comment]
Спасибо. Исправил. Не думал что расширение уже используется, ведь нет даже описания :).

**Comment by Insolita** [comment]
пока еще не использую. дошли руки поковырять, обовляю кейс c очередями еще на базе 0.11 до текущей (больше 3 месяцев в проде отработал :-) )
вообще бы презентер какой для методов вместо ` Wait: <?= $f->asInteger($model->firstExec->reserved_at - $model->pushed_at - $model->delay) ?>s`
` Exec: <?= $f->asInteger($model->lastExec->done_at - $model->lastExec->done_at) ?>s`
или в модель прямо... их не так много
а в идеале проброску через модуль или через контейнер чтоб модели можно было подменить не через классмап, а не только названия таблиц

**Comment by zhuravljov** [comment]
> пока еще не использую. дошли руки поковырять, обовляю кейс c очередями еще на базе 0.11 до текущей (больше 3 месяцев в проде отработал :-) )

На редисе, если я правильно помню из переписки? В качестве текущей стоит брать dev-master. Там для редис-драйвера был исправлен баг с отложенными сообщениями. Фикс попадет в 2.0.1.

> вообще бы презентер какой для методов вместо
> https://github.com/zhuravljov/yii2-queue-monitor/blob/master/src/views/job/_index-item.php#L37
> https://github.com/zhuravljov/yii2-queue-monitor/blob/master/src/views/job/_index-item.php#L32
> https://github.com/zhuravljov/yii2-queue-monitor/blob/master/src/views/job/view-data.php#L21 или в модель прямо... их не так много

Да, спасибо, сделаю.

> а в идеале проброску через контейнер чтоб модели можно было подменить не через классмап, а не только названия таблиц

Тоже будет. Пока разработка в самом начале. Сначала хочу проработать пользовательский интерфейс.

Собираю статистику на своих проектах, чтобы определиться какую информацию и в каком виде выводить пользователю, чтобы можно было с одного взгляда оценить эффективность очередей, и, если нужно, то в пару кликов добраться проблемных точек.

**Comment by Insolita** [comment]
да, на редиске, про dev-master в курсе
По интерфейсу ..на вкус и цвет фломастеры разные, думаю тут как раз большинство под себя пилить будет, многие на adminLte сидят. или ты в конкуренты laravel-horizon хочешь? :-)
А вообще пока у нас просто табличка, все устраивало... перезапуски просто новые записи создавали с указанием id базового без спец.фиксации http://joxi.ru/LmG793wFeNoOVm

**Comment by zhuravljov** [comment]
> или ты в конкуренты laravel-horizon хочешь? :-)

И да и нет, но рано или поздно это должно было прозвучать :).

Нет, потому что идея родилась [здесь](https://github.com/yiisoft/yii2-queue/issues/52#issuecomment-302498112) в переписке с твоей подачи, когда Horizon не только не анонсировали, но и не [начали делать](https://github.com/laravel/horizon/commit/daab248c6802f3dd9cf596934a98e7363064841e).

И, да, потому что Тейлор собрал в кучу все, что полезно знать про очередь, и Horizon выглядит как хороший пример.

Еще присматриваюсь к Sidekiq. Похожая система мониторинга из мира Ruby.

**Comment by Insolita** [comment]
Еще несколько вопросов возникло - 1. миграции без внешних ключей это норм или пока просто руки не дошли?
2. А не было варианта статус вычислять/обновлять непосредственно в поведении и сразу сохранять в поле статус, а не постфактум? Можно было бы фильтрацию по нескольким статусам делать, и для статистики удобнее

**Comment by zhuravljov** [comment]
> 1. миграции без внешних ключей это норм или пока просто руки не дошли?

Пока не уверен нужны ли они. Возможно будет проще проигнорировать контроль связей на уровне БД, в пользу уровня приложения. Хочется обеспечить поддержку mysql, pgsql и sqlite, с уверенностью что контроль целостности будет работать одинаково. В общем, отложил этот вопрос на потом, как не приоритетный.

> 2. А не было варианта статус вычислять/обновлять непосредственно в поведении и сразу сохранять в поле статус, а не постфактум?

В том виде как есть сейчас статусы задач отличаются от поисковых статусов.

Первые только на отображение, из расчета что у задания в один момент времени может быть только один статус. Но не все из них нужны для фильтрации. Например, кратковременный статус задания "restarted" имеет смысл для вывода в списке, но бесполезен для выборки.

Вторые по факту являются поисковыми скоупами (наверное стоит переименовать), в которые могут попадать задания с разными статусами, а одно и то же задание может попадать в несколько скоупов. Например в скоуп "has-fails" могут попадать задания со всеми статусами кроме "waiting" и "started".

> Можно было бы фильтрацию по нескольким статусам делать

Думал над этим. Есть мысль отойти от стандартной поисковой формы yii, в пользу поисковой строки как в github issues. Типа "is:issue is:open". Чтобы можно было комбинировать условия.

**Comment by Insolita** [comment]
Ну чисто так в качестве идей, что у нас получилось по интерфейсу, 
http://joxi.ru/82QWB7wtjaOqer
http://joxi.ru/L2136jkU8N4oZr
Блок с фильтром position:fixed, убрали фильтры по id и delay - как то практической необходимости у нас не было, добавили выбор сортировки (id,pushed_at,delay) и кол-во на страницу
Кнопки управления сразу, инфа  разворачивается, на отдельной странице только просмотра таблицы попыток с трейсом ошибок

**Comment by zhuravljov** [comment]
Спасибо за идеи. Фиксированная позиция фильтра - хорошая идея. Нужно будет прикрутить affix плагин под это дело. Поиск по id и delay тоже выпилил за ненадобностью. Сортировку и кол-во записей на страницу тоже сделаю, но не через форму, а отдельными контролами. Чтобы фильтр можно было использовать и для страницы со списком задач, и для страницы статистики.

**Comment by ignatenkovnikita** [comment]
Блин как плохо, что только сейчас нашел это расширение ((( 
Пришлось вчера накидать свой для мониторинга очередями) 
https://github.com/ignatenkovnikita/yii2-queuemanager

Поставил расширение прикольно, только заметил, что статусы о выполнении задач приходят с опозданием
С чем связано это ?

**Comment by zhuravljov** [comment]
> Блин как плохо, что только сейчас нашел это расширение (((

Расширение хоть и стабильно, но еще на стадии глубокой разработки. Поэтому нет описания, и пока нигде не опубликовано.

> Поставил расширение прикольно, только добавить бы ajax обновление

Да, хорошая идея. Сделаю.

**Comment by ignatenkovnikita** [comment]
> Расширение хоть и стабильно, но еще на стадии глубокой разработки. Поэтому нет описания, и пока нигде не опубликовано.

Ну я бы хотя его взял за основу, а то пришлось свое пилить)
