### ISSUE TITLE
clear-deprecated console command 

### ISSUE THREAD

**Issue by yuldashevsardor** [zhuravljov/yii2-queue-monitor#20]
Команда clear-deprecated удаляет только те строки у которых `last_exec.retry = false`. Но retry так же может быть и null. Это ошибка или есть причины удалять только `retry = true`?

**Comment by zhuravljov** [comment]
`null` будет если задание в процессе выполнения; `retry = true` - выполнение завершилось с ошибкой (исключением), и остается в резерве очереди до следующей попытки; `retry = false` - выполнено успешно, либо выполнено с ошибкой, но попыток перевыполнить больше не будет.
Команда `clear-deprecated` удаляет все устаревшие задания, обработка которых полностью завершена. Это определяется по `retry = false` последней попытки.

**Comment by yuldashevsardor** [comment]
Задачи запускаются через обычный JobInterface, не RetryableJobInterface. 
Что заметил :
- Если задача была завершена с ошибкой - `retry = false`
- Если задача была завершена успешно - `retry is null`

Куда копать?

**Comment by yuldashevsardor** [comment]
Пробежался дебагером, что выяснил:
- Когда джоб выполнился с ошибкой - как положено `retry = false`
- Когда джоб выполнился успешно:
  - [тут](https://github.com/zhuravljov/yii2-queue-monitor/blob/da4ce413951112620ee35ef8d26769b542a19fa4/src/JobMonitor.php#L160) `$event->retry = null`
  - [тут](https://github.com/zhuravljov/yii2-queue-monitor/blob/da4ce413951112620ee35ef8d26769b542a19fa4/src/JobMonitor.php#L169) проверку на `isStopped` не проходит (`stopped_at = null`), соответвенно дальше идет инсерт с `retry = null`

**Comment by zhuravljov** [comment]
Да похоже так и есть. При успешном выполнении значение `$event->retry` остается дефолтным. На условные блоки на уровне `yiisoft/yii2-queue` это не влияет, потому как `null` приводится к `false`, а вот в базу мониторинга пишется некорректное значение. Теперь проблема понятна, спасибо.

**Comment by zhuravljov** [comment]
Исправил, спасибо.
