### ISSUE TITLE
Не изменяется статус некоторых заданий при запуске

### ISSUE THREAD

**Issue by lusy777** [zhuravljov/yii2-queue-monitor#22]
Для запуска заданий из таблицы queue использую listeners для двух очередей. 
В первой очереди при запуске/ выполнении третьего и последующего задания - не меняет статус на "started" и "done". Задания остаются как "waiting".
Во второй очереди аналогичная ситуация после выполнения первого задания.
Сначала была мысль, что очередь не выполняет задания, но после проверки, очередь выполняет все задания, не меняются только статусы заданий.

**Comment by zhuravljov** [comment]
Что вы имеете в виду когда говорите про две очереди? Очередь одна. Может вы про два воркера `queue/listen`?

Не достаточно информации, чтобы понять суть проблемы. Покажите как вы конфигурируете очередь, какие команды запускаете для её обработки.

**Comment by lusy777** [comment]
Да, извиняюсь. Имеется ввиду два воркера. Мы протестировали около 200 jobs и половина из них на мониторе остается как waiting, другая половина проходит корректный путь "waiting" -> "started" -> "done".
config/web:
```'bootstrap' => ['log', 'monitor', 'scheduler', 'queue1', 'queue2'],```

```
     'queue1' => [
            'class' => \yii\queue\db\Queue::class,
            'db' => 'db',
            'ttr' => 10800,
            'tableName' => 'queue',
            'channel' => 'default',
            'as log' => \yii\queue\LogBehavior::class,
            'mutex' => \yii\mutex\MysqlMutex::class,
            'as jobMonitor' => \zhuravljov\yii\queue\monitor\JobMonitor::class,
            'as workerMonitor' => \zhuravljov\yii\queue\monitor\WorkerMonitor::class,
        ],
        'queue2' => [
            'class' => \yii\queue\db\Queue::class,
            'db' => 'db',
            'ttr' => 10800,
            'tableName' => 'queue',
            'channel' => 'default',
            'as log' => \yii\queue\LogBehavior::class,
            'mutex' => \yii\mutex\MysqlMutex::class,
            'as jobMonitor' => \zhuravljov\yii\queue\monitor\JobMonitor::class,
            'as workerMonitor' => \zhuravljov\yii\queue\monitor\WorkerMonitor::class,
        ],
```

Планировщик запускает команду push, который добавляет в очередь первый или второй воркер
```
Yii::$app->queue1->push(new SomeJob());
```
В качестве SomeJob запускали функцию sleep() на рандомное время.
Все jobs отрабатываются очередью, но не все записываются в queue_exec table и соответственно не меняют статуса с waiting.

**Comment by zhuravljov** [comment]
Ошибка в том, что вы используете две разные очереди, но с одним общим хранилищем. И выходит так, что событие отправки задания в очередь  происходит для очереди `queue1`, а обрабока этого задания выполняется воркером для `queue2`. Мониторинг не видит такие выполнения потому, что в `queue2` это задание никто не отправлял.

Если для обоих очередей используется `db\Queue`, то должны быть либо разные таблицы, либо разные каналы в рамках одной таблицы.

И, кстати, с чем связана необходимость в двух очередях?

**Comment by lusy777** [comment]
Спасибо за ваше разъяснение, но почему, как вы говорите, отправляет задание один воркер, а выполняет другой? В коде четко разграничиваю отправление задания или первым или вторым, как:
`$app->queue1->push` или `$app->queue2->push`
и после события отправки воркер записывается в таблицу, т.е. теоретически при событии выполнения задание должен обрабатывать тот же самый воркер, то и отправлял в очередь, разве нет?

`И, кстати, с чем связана необходимость в двух очередях?`
На самом деле, мы планируем большее количество очередей, потому что заданий сейчас около 60. Некоторые из них должны запускаться в строго ограниченное время, минута в минуту, то есть впереди него не должно быть никаких других заданий, которые могут занять то самое назначенное время. К тому же выполнение одного задания может быть длительным и чтобы не ломать интервал запуска заданий, мы будем создавать новые очереди.

Похоже, что в нашем случае создание разных таблиц не имеет смысла, но разные каналы будут ли выходом, скажем для 10 и более очередей?

**Comment by zhuravljov** [comment]
> т.е. теоретически при событии выполнения задание должен обрабатывать тот же самый воркер, то и отправлял в очередь, разве нет?

В общем - да, но не с вашим конфигом. У вас для обоих очередей одинаковые настройки хранилища (`tableName` и `channel`). Сделайте их с разными каналами:

```php
'queue1' => [
    //...
    'channel' => 'channel1',
],
'queue2' => [
    //...
    'channel' => 'channel2',
],
```

> Похоже, что в нашем случае создание разных таблиц не имеет смысла, но разные каналы будут ли выходом, скажем для 10 и более очередей?

Да, это будет работать. На уровне БД `channel` это проиндексированное поле в таблице `queue`. И тут дело не столько в кол-ве очередей, сколько в плотности потока заданий. Если проект нагруженный и поток заданий большой, обычно выбирают более специализировнные решения типа RabbitMQ. Redis так же неплохо себя показывает в качестве брокера очередей.

**Comment by lusy777** [comment]
> Сделайте их с разными каналами:

ок, отличное решение. Подскажите еще, пожалуйста, как при этом изменятся команды для запуска?
Например, сейчас я запускаю это как:
`php yii queue1/listen`
`php yii queue2/listen`

**Comment by zhuravljov** [comment]
Все верно вы запускаете, и теперь это будет работать корректно.

**Comment by lusy777** [comment]
Спасибо большое за помощь!!!

**Comment by zhuravljov** [comment]
Пожалуйста
