### ISSUE TITLE
Tests has failed after adding workerMonitor behaviour to queue component

### ISSUE THREAD

**Issue by sashsvamir** [zhuravljov/yii2-queue-monitor#9]
My functional tests have runs queue manually like this:
```php
$queue = $I->grabComponent('queue');
$queue->clear();
// ... Here i open route with adding some job... Next i run queue:
$queue->run(false);
```
But this lead to exception `Queue must be an application component` because in `WorkerMonitor::getSenderName` method `Yii::$app->getComponents(false)` return array with no queue component.
Where i wrong here and how can i fix this?

**Comment by zhuravljov** [comment]
You can turn the behavior off in your test configuration.

**Comment by sashsvamir** [comment]
offer to add note how to disable monitor behaviours to readme:
pr #10

**Comment by sashsvamir** [comment]
I'm resolved subject problem. If somebody need solution: to work monitor behaviours on manual run queue in tests, you should grab queue component straight before running queue or after submiting form, like this:
```php
$queue = $I->grabComponent('queue');
$queue->clear();
// open route and submit the form (leads to adding some job):
$I->amOnRoute('...');
$I->submitForm('...');
// grab queue component and run queue:
$queue = $I->grabComponent('queue');
$queue->run(false);
```
